Feature shortcuts dinamicos
kunder-lab/cordova-plugin-kunder-android-shortcuts pull request #1
Opened 2018-03-12 15:17 UTC by sebalagos90

- Se crea el método para crear shortcuts dinámicos.
- Se crea el método para eliminar todos los shortcuts dinámicos.
- Se actualizan los archivos README.

2018-03-12 17:50 UTC, xchopox requested changes
Verificar sugerencias especificadas en comentarios.

2018-03-12 17:50 UTC, xchopox commented on README.md
> +Create android-shortcuts.json file in project's root folder with all the information about the shortcuts you want to create (maximum 4 shortcuts):
[S:0] Se sugiere dejar el comienzo de la frase como: "Create a JSON file called `android-shortcuts.json` in the root folder of the project..." o "Create the `android-shortcuts.json` file in the root folder of the project... ".

2018-03-12 17:50 UTC, xchopox commented on README.md
> +This plugin allows you the following method to create shortcuts dynamically (on runtime):
[S:0] "This plugin allows you `to use` the following method..."

2018-03-12 17:50 UTC, xchopox commented on README.md
> +Use the following method to remove all dynamic shortcuts. This will not remove static shortcuts:
[S:0] "This will not remove `the` static shortcuts:"

2018-03-12 17:50 UTC, xchopox commented on src/android/cl/kunder/androidshortcuts/AndroidShortcutsPlugin.java
> +            if(shortcutManager.getDynamicShortcuts().size() == 4) {
[S:1] Favor de verificar condicional para los shortcuts estáticos.

2018-03-12 19:23 UTC, sebalagos90 commented on README.md
> +This plugin allows you the following method to create shortcuts dynamically (on runtime):
My bad, tenía que haber sido "This plugin provides you ..."

2018-03-19 14:55 UTC, xchopox approved these changes
Cambios aprobados.

2018-03-19 15:20 UTC, merged